# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


          
      - name: selenium & beautifulsoup4
        run: |
          pip install selenium
          pip install beautifulsoup4
          
      - name: Instalacion de Google Chrome y chromedriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo rm google-chrome-stable_current_amd64.deb
          wget https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          google-chrome --version
          
      - name: Instala las dependencias necesarias en tu sistema
        run: |
          sudo apt-get install -y xvfb
          sudo apt-get install -y x11-utils
          sudo apt-get install -y xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic
          
      - name: Permisos chromedriver
        run: |
          sudo chown root:root chromedriver
          sudo chmod +x chromedriver
          
      - name: virtualdisplay
        run: |
          pip install pyvirtualdisplay
          python3 selenium_src.py
          ls
          
